POST http://localhost:5173/api/user
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImpvaG5kb2UiLCJlbWFpbCI6ImpvaG5kb2VAbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJqb2huIiwibGFzdE5hbWUiOiJkb2UiLCJyb2xlIjoiVVNFUiJ9fQ.t5Of2qyqtxm7XNurm3N-7mWJe4W79F1QdH7UENwtN1U

{
  "user": {
    "username": "johndoe",
    "password": "test"
  }
}

